### ISSUE TITLE
main.go

### ISSUE THREAD

**Issue by 2313V** [def670/ethoclub#1]
Hello, it's main.go up to date?

When i clone and compile "make", it return error on  - github.com/yvasiyarov/gorelic

Makefile:10: recipe for target 'all' failed
make: *** [all] Error 2

i think the "github.com/yvasiyarov/gorelic" is not working anymore.

Can you give a look?

I also tried in ubuntu 18 server and gave me other error
![Captura de ecrã 2022-06-29 201303](https://user-images.githubusercontent.com/108402149/176517681-08853bc6-7eca-499e-9c99-6ea7eb42b600.jpg)
.

**Comment by def670** [comment]
enter this in your terminal
export GO111MODULE=auto
then
make clean
make

let me know if that fixes your issue

**Comment by def670** [comment]
should run on ubuntu 16.04 but i highly recommend 18+

**Comment by 2313V** [comment]
It worked. Thanks.

Now i think i have configuration issues (not related to this)

**Comment by def670** [comment]
no problem.  im gonna close this due to the above solution fixing the issue.
